-- Review Annotator: database schema, privacy rules, queues, and statistics.
-- Run this entire file once in the Supabase SQL Editor.

create type public.app_role as enum ('annotator', 'adjudicator', 'admin');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'New user',
  role public.app_role not null default 'annotator',
  created_at timestamptz not null default now()
);

create table public.reviews (
  id bigint generated by default as identity primary key,
  candidate_id text not null unique,
  review_text text not null check (length(trim(review_text)) > 0),
  source_tier text not null default 'IMPORTED',
  source_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.annotations (
  review_id bigint not null references public.reviews(id) on delete cascade,
  annotator_id uuid not null references public.profiles(id) on delete cascade,
  complaint_present boolean not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (review_id, annotator_id)
);

create table public.review_skips (
  review_id bigint not null references public.reviews(id) on delete cascade,
  annotator_id uuid not null references public.profiles(id) on delete cascade,
  skipped_at timestamptz not null default now(),
  primary key (review_id, annotator_id)
);

create table public.adjudications (
  review_id bigint primary key references public.reviews(id) on delete cascade,
  adjudicator_id uuid not null references public.profiles(id) on delete restrict,
  final_complaint_present boolean not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index annotations_annotator_idx on public.annotations (annotator_id, review_id);
create index skips_annotator_idx on public.review_skips (annotator_id, skipped_at);
create index reviews_queue_idx on public.reviews (active, source_tier, source_order, id);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'display_name', split_part(new.email, '@', 1)));
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.current_app_role()
returns public.app_role language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

alter table public.profiles enable row level security;
alter table public.reviews enable row level security;
alter table public.annotations enable row level security;
alter table public.review_skips enable row level security;
alter table public.adjudications enable row level security;

create policy "users read own profile" on public.profiles for select
using (id = auth.uid() or public.current_app_role() = 'admin');
create policy "admins update profiles" on public.profiles for update
using (public.current_app_role() = 'admin') with check (public.current_app_role() = 'admin');

create policy "admins manage reviews" on public.reviews for all
using (public.current_app_role() = 'admin') with check (public.current_app_role() = 'admin');

create policy "annotators read own annotations" on public.annotations for select
using (annotator_id = auth.uid() or public.current_app_role() = 'admin');
create policy "annotators insert own annotations" on public.annotations for insert
with check (annotator_id = auth.uid() and public.current_app_role() = 'annotator');
create policy "annotators update own annotations" on public.annotations for update
using (annotator_id = auth.uid() and public.current_app_role() = 'annotator')
with check (annotator_id = auth.uid() and public.current_app_role() = 'annotator');
create policy "annotators delete own annotations" on public.annotations for delete
using (annotator_id = auth.uid() and public.current_app_role() = 'annotator');

create policy "annotators manage own skips" on public.review_skips for all
using (annotator_id = auth.uid() and public.current_app_role() = 'annotator')
with check (annotator_id = auth.uid() and public.current_app_role() = 'annotator');

create policy "adjudicators read final labels" on public.adjudications for select
using (adjudicator_id = auth.uid() or public.current_app_role() = 'admin');
create policy "adjudicators insert final labels" on public.adjudications for insert
with check (adjudicator_id = auth.uid() and public.current_app_role() = 'adjudicator');
create policy "adjudicators update final labels" on public.adjudications for update
using (adjudicator_id = auth.uid() and public.current_app_role() = 'adjudicator')
with check (adjudicator_id = auth.uid() and public.current_app_role() = 'adjudicator');

create or replace function public.next_review_for_current_user()
returns table (id bigint, candidate_id text, review_text text, source_tier text)
language sql stable security definer set search_path = public as $$
  select r.id, r.candidate_id, r.review_text, r.source_tier
  from public.reviews r
  left join public.review_skips s on s.review_id = r.id and s.annotator_id = auth.uid()
  where r.active
    and public.current_app_role() = 'annotator'
    and not exists (
      select 1 from public.annotations a
      where a.review_id = r.id and a.annotator_id = auth.uid()
    )
  order by
    case when s.review_id is null then 0 else 1 end,
    case r.source_tier when 'TIER_A_CONFIDENT' then 1 when 'TIER_B_LIKELY' then 2 when 'TIER_C_RECHECK' then 3 else 4 end,
    case when s.review_id is null then r.source_order else extract(epoch from s.skipped_at)::integer end,
    r.id
  limit 1;
$$;

create or replace function public.annotation_progress()
returns table (total bigint, completed bigint, skipped bigint)
language sql stable security definer set search_path = public as $$
  select
    (select count(*) from public.reviews where active),
    (select count(*) from public.annotations where annotator_id = auth.uid()),
    (select count(*) from public.review_skips s where s.annotator_id = auth.uid()
      and not exists (select 1 from public.annotations a where a.review_id = s.review_id and a.annotator_id = auth.uid()));
$$;

create or replace function public.annotation_pairs()
returns table (
  review_id bigint,
  annotator_1_id uuid, annotator_1_complaint boolean,
  annotator_2_id uuid, annotator_2_complaint boolean
)
language sql stable security definer set search_path = public as $$
  with ranked as (
    select a.*, row_number() over (partition by a.review_id order by a.created_at, a.annotator_id) as rn
    from public.annotations a
    join public.profiles p on p.id = a.annotator_id and p.role = 'annotator'
  )
  select one.review_id,
    one.annotator_id, one.complaint_present,
    two.annotator_id, two.complaint_present
  from ranked one join ranked two on two.review_id = one.review_id and two.rn = 2
  where one.rn = 1;
$$;

create or replace function public.next_disagreement_for_current_user()
returns table (
  id bigint, candidate_id text, review_text text, source_tier text,
  annotator_1_complaint boolean, annotator_2_complaint boolean
)
language sql stable security definer set search_path = public as $$
  select r.id, r.candidate_id, r.review_text, r.source_tier,
    p.annotator_1_complaint, p.annotator_2_complaint
  from public.annotation_pairs() p
  join public.reviews r on r.id = p.review_id
  where public.current_app_role() = 'adjudicator'
    and p.annotator_1_complaint <> p.annotator_2_complaint
    and not exists (select 1 from public.adjudications j where j.review_id = r.id)
  order by case r.source_tier when 'TIER_A_CONFIDENT' then 1 when 'TIER_B_LIKELY' then 2 when 'TIER_C_RECHECK' then 3 else 4 end,
    r.source_order, r.id
  limit 1;
$$;

create or replace function public.binary_kappa(n11 numeric, n10 numeric, n01 numeric, n00 numeric)
returns numeric language sql immutable as $$
  select case
    when n11 + n10 + n01 + n00 = 0 then null
    when 1 - (((n11+n10)*(n11+n01) + (n01+n00)*(n10+n00)) / power(n11+n10+n01+n00, 2)) = 0 then null
    else (
      ((n11+n00)/(n11+n10+n01+n00))
      - (((n11+n10)*(n11+n01) + (n01+n00)*(n10+n00)) / power(n11+n10+n01+n00, 2))
    ) / (
      1 - (((n11+n10)*(n11+n01) + (n01+n00)*(n10+n00)) / power(n11+n10+n01+n00, 2))
    )
  end;
$$;

create or replace function public.admin_overview()
returns jsonb language sql stable security definer set search_path = public as $$
  with pairs as (select * from public.annotation_pairs()),
  complaint_counts as (
    select
      count(*) filter (where annotator_1_complaint and annotator_2_complaint)::numeric n11,
      count(*) filter (where annotator_1_complaint and not annotator_2_complaint)::numeric n10,
      count(*) filter (where not annotator_1_complaint and annotator_2_complaint)::numeric n01,
      count(*) filter (where not annotator_1_complaint and not annotator_2_complaint)::numeric n00
    from pairs
  ),
  base as (
    select
      (select count(*) from public.reviews where active) total_reviews,
      (select count(*) from pairs) double_annotated,
      (select count(*) from pairs p where p.annotator_1_complaint <> p.annotator_2_complaint and not exists (select 1 from public.adjudications j where j.review_id = p.review_id)) pending_disagreements,
      (select count(*) from public.adjudications) adjudicated
  )
  select case when public.current_app_role() <> 'admin' then null else jsonb_build_object(
    'total_reviews', base.total_reviews,
    'double_annotated', base.double_annotated,
    'pending_disagreements', base.pending_disagreements,
    'adjudicated', base.adjudicated,
    'complaint_kappa', public.binary_kappa(c.n11,c.n10,c.n01,c.n00),
    'complaint_agreement_percent', round(100 * (c.n11+c.n00) / nullif(c.n11+c.n10+c.n01+c.n00,0), 1),
    'annotators', coalesce((
      select jsonb_agg(jsonb_build_object('id', p.id, 'name', p.display_name, 'completed', coalesce(x.completed,0)) order by p.created_at)
      from public.profiles p
      left join (select annotator_id, count(*) completed from public.annotations group by annotator_id) x on x.annotator_id = p.id
      where p.role = 'annotator'
    ), '[]'::jsonb)
  ) end
  from base cross join complaint_counts c;
$$;

create or replace function public.export_final_dataset()
returns table (
  candidate_id text, review_text text, source_tier text,
  annotation_status text,
  annotator_1_complaint boolean, annotator_2_complaint boolean,
  final_complaint_present boolean
)
language sql stable security definer set search_path = public as $$
  select r.candidate_id, r.review_text, r.source_tier,
    case
      when j.review_id is not null then 'adjudicated'
      when p.review_id is null then 'incomplete'
      when p.annotator_1_complaint = p.annotator_2_complaint then 'agreed'
      else 'needs_adjudication'
    end,
    p.annotator_1_complaint, p.annotator_2_complaint,
    case
      when j.review_id is not null then j.final_complaint_present
      when p.annotator_1_complaint = p.annotator_2_complaint then p.annotator_1_complaint
      else null
    end
  from public.reviews r
  left join public.annotation_pairs() p on p.review_id = r.id
  left join public.adjudications j on j.review_id = r.id
  where public.current_app_role() = 'admin' and r.active
  order by case r.source_tier when 'TIER_A_CONFIDENT' then 1 when 'TIER_B_LIKELY' then 2 when 'TIER_C_RECHECK' then 3 else 4 end,
    r.source_order, r.id;
$$;

revoke all on function public.annotation_pairs() from public;
grant execute on function public.next_review_for_current_user() to authenticated;
grant execute on function public.annotation_progress() to authenticated;
grant execute on function public.next_disagreement_for_current_user() to authenticated;
grant execute on function public.admin_overview() to authenticated;
grant execute on function public.export_final_dataset() to authenticated;
