-- Private review discussions for the two primary annotators.
-- A review becomes discussable only after both annotators have submitted labels.

create table if not exists public.review_discussion_messages (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check (length(trim(message)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists review_discussion_messages_review_idx
  on public.review_discussion_messages (review_id, created_at, id);

alter table public.review_discussion_messages enable row level security;

-- Add discussion readiness to the annotator's label history so the interface
-- never invites discussion before the partner has submitted a label.
drop function if exists public.all_annotations_for_current_user();

create or replace function public.all_annotations_for_current_user()
returns table (
  id bigint,
  candidate_id text,
  review_text text,
  source_tier text,
  label public.annotation_label,
  updated_at timestamptz,
  annotation_number bigint,
  discussion_ready boolean
)
language sql stable security definer set search_path = public as $$
  with numbered as (
    select
      r.id,
      r.candidate_id,
      r.review_text,
      r.source_tier,
      a.label,
      a.updated_at,
      row_number() over (order by a.created_at, r.id) as annotation_number,
      exists (
        select 1 from public.annotation_pairs() pair
        where pair.review_id = r.id
      ) as discussion_ready
    from public.annotations a
    join public.reviews r on r.id = a.review_id
    where a.annotator_id = auth.uid()
      and public.current_app_role() = 'annotator'
  )
  select * from numbered order by annotation_number desc;
$$;

create or replace function public.discussion_reviews_for_current_user()
returns table (
  id bigint,
  candidate_id text,
  review_text text,
  source_tier text,
  annotator_1_label public.annotation_label,
  annotator_2_label public.annotation_label,
  message_count bigint,
  last_message_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    r.id,
    r.candidate_id,
    r.review_text,
    r.source_tier,
    p.annotator_1_label,
    p.annotator_2_label,
    count(m.id) as message_count,
    max(m.created_at) as last_message_at
  from public.annotation_pairs() p
  join public.reviews r on r.id = p.review_id
  left join public.review_discussion_messages m on m.review_id = r.id
  where public.current_app_role() in ('annotator', 'admin')
    and r.active
  group by r.id, r.candidate_id, r.review_text, r.source_tier,
    r.source_order, p.annotator_1_label, p.annotator_2_label
  order by max(m.created_at) desc nulls last, r.source_order, r.id;
$$;

create or replace function public.discussion_messages_for_review(target_review_id bigint)
returns table (
  id bigint,
  review_id bigint,
  author_id uuid,
  author_name text,
  author_role public.app_role,
  message text,
  created_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    m.id,
    m.review_id,
    m.author_id,
    p.display_name,
    p.role,
    m.message,
    m.created_at
  from public.review_discussion_messages m
  join public.profiles p on p.id = m.author_id
  where m.review_id = target_review_id
    and public.current_app_role() in ('annotator', 'admin')
    and exists (
      select 1
      from public.annotation_pairs() pair
      where pair.review_id = target_review_id
    )
  order by m.created_at, m.id;
$$;

create or replace function public.post_review_discussion_message(
  target_review_id bigint,
  target_message text
)
returns table (
  id bigint,
  review_id bigint,
  author_id uuid,
  author_name text,
  author_role public.app_role,
  message text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  clean_message text := trim(target_message);
  inserted_id bigint;
begin
  if auth.uid() is null or public.current_app_role() <> 'annotator' then
    raise exception 'Only signed-in annotators can post messages';
  end if;

  if length(clean_message) < 1 or length(clean_message) > 2000 then
    raise exception 'Messages must contain between 1 and 2000 characters';
  end if;

  if not exists (
    select 1
    from public.annotation_pairs() pair
    where pair.review_id = target_review_id
  ) then
    raise exception 'This review can be discussed after both annotators submit labels';
  end if;

  insert into public.review_discussion_messages (review_id, author_id, message)
  values (target_review_id, auth.uid(), clean_message)
  returning review_discussion_messages.id into inserted_id;

  return query
  select
    m.id,
    m.review_id,
    m.author_id,
    p.display_name,
    p.role,
    m.message,
    m.created_at
  from public.review_discussion_messages m
  join public.profiles p on p.id = m.author_id
  where m.id = inserted_id;
end;
$$;

revoke all on table public.review_discussion_messages from public;
revoke all on function public.discussion_reviews_for_current_user() from public;
revoke all on function public.discussion_messages_for_review(bigint) from public;
revoke all on function public.post_review_discussion_message(bigint, text) from public;

grant execute on function public.discussion_reviews_for_current_user() to authenticated;
grant execute on function public.discussion_messages_for_review(bigint) to authenticated;
grant execute on function public.post_review_discussion_message(bigint, text) to authenticated;
grant execute on function public.all_annotations_for_current_user() to authenticated;
